- name: disable current version of sql
  ansible.builtin.command: dnf module disable mysql -y

- name: setup mysql5.7 repo
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

# - name: install mysql server
#   ansible.builtin.package:
#     name: mysql-community-server
#     state: present

- name: Install mysql Server
  ansible.builtin.dnf:
    name: mysql-server
    state: latest

- name: start and enable mysql
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: setup root password
  ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1


#   - name: Install MySQL Server
#   ansible.builtin.dnf:
#     name: mysql-server
#     state: latest

# - name: Start and Enable MySQL server
#   ansible.builtin.service:
#     name: mysqld
#     state: started
#     enabled: yes

# - name: install python mysql dependencies
#   ansible.builtin.pip:
#     name:
#     - PyMySQL
#     - cryptography
#     executable: pip3.9 # pip3.11 if python version is 3.11

# - name: ansible to install pymysql
#   ansible.builtin.pip:
#     name:
#     - PyMySQL
#     executable: pip3.9

# - name: install MySQL Server
#   ansible.builtin.package:
#     name: mysql-server
#     state: present

# - name: start mysql server
#   ansible.builtin.service:
#     name: mysqld
#     state: started
#     enabled: yes

# - name: connect mysql server
#   community.mysql.mysql_info:
#     login_user: root
#     login_password: "{{ mysql_root_password }}"
#     login_host: "{{ login_host }}"
#   ignore_errors: true
#   register: mysql_info